### ISSUE TITLE
Support modules with multiple flows/data stores

### ISSUE THREAD

**Issue by shlomitk1** [IBM/the-mesh-for-data#103]
Problem statement: a module that can support multiple flows, e.g. read and write, or multiple datasets should be instantiated once. However, the current version will instantiate multiple instances of the same module.

Use-case 1: two data sets A and B, a single read module is selected for both. Currently, the blueprint contains two instances of a module: one for A, another for B. We want a single instance of the module for both A and B.

Use-case 2: A single module supports both read and write. Currently, the blueprint contains two instances of a module: for read and for write. We want a single instance of the module with both read and write sections inside its arguments.

Required:
- to remove oneOf selector in ModuleArguments
- to unite instances of the same module into one inside the blueprint

Affected components: manager (blueprint generation)

**Comment by simanadler** [comment]
> Problem statement: a module that can support multiple flows, e.g. read and write, or multiple datasets should be instantiated once. However, the current version will instantiate multiple instances of the same module.
> 
> Use-case 1: two data sets A and B, a single read module is selected for both. Currently, the blueprint contains two instances of a module: one for A, another for B. We want a single instance of the module for both A and B.

@shlomitk1 @roee88 @ronenkat 
1) What about transformations?  Will the transformations be per data set, or do they have to match in order to be merged into a single instance?

2) As we move to multi-cloud I think the logic will be more complex than this.  Since we will begin multi-cloud work shortly, I suggest to wait before making this change.

> 
> Use-case 2: A single module supports both read and write. Currently, the blueprint contains two instances of a module: for read and for write. We want a single instance of the module with both read and write sections inside its arguments.
> 
> Required:
> 
>     * to remove oneOf selector in ModuleArguments
> 
>     * to unite instances of the same module into one inside the blueprint
> 
@shlomitk1 
Same comments as the previous scenario 
> 
> Affected components: manager (blueprint generation)

@shlomitk1 @roee88 @ronenkat  As we move to multi-cluster we need to think whether this optimization will be done by the blueprint generator or by the blueprint controller.

**Comment by shlomitk1** [comment]
@simanadler Transformations are a part of the Read, together with source and destination.
Suppose we have a dataset that needs to be read from S1 while performing action1 and action2, in addition to a dataset that needs to be read from S2 while performing action3.
Instead of a read module for reading from S1 doing action1,action2 AND another read module reading from S2 doing action3 we'll get a single read module that will (1) read from S1 doing action1,action2 AND (2) read from S2 doing action3.

**Comment by shlomitk1** [comment]
> 
> @shlomitk1 @roee88 @ronenkat As we move to multi-cluster we need to think whether this optimization will be done by the blueprint generator or by the blueprint controller.

Today we have a single namespace for running all pods. If some pods are running in one namespace, others - in another, then merging them together does not make sense. What are the implications of multi-cluster: will we have several control planes? several blueprints?

**Comment by roee88** [comment]
I don't see why multi-cluster should block this.
