### ISSUE TITLE
BacthTransfer deletion fails

### ISSUE THREAD

**Issue by shlomitk1** [IBM/the-mesh-for-data#105]
When an m4dapplication is deleted, two things happen: the relevant blueprint is deleted, and the allocated namespace is deleted.
Deletion of a blueprint causes uninstall of a Helm release which deletes a batchtransfer resource if exists. However, batchtransfer is not deleted, and the namespace is stuck in Terminating status.

**Comment by froesef** [comment]
This is due to the fact that the BatchTransfer is starting a finaliser pod when it gets deleted. But when the namespace is terminating it cannot create any new objects in there. So we need to wait for deleting the namespace until all the finalisers and objects have been deleted.

**Comment by roee88** [comment]
Sounds like an issue in the finalizer design, because normally deleting a namespace shouldn't block (think of human users of the motion API as well). Was this design pattern taken from another project? If so, can you share which?

**Comment by froesef** [comment]
No I came up with the design pattern myself. The thought behind was that the mover knows best how to talk to the stores. 
Removing a file from COS would probably not be a problem in go. But when accessing other stores like Kafka would bring in all Kafka dependencies into the manager then. (e.g. when the finalizer there should remove a topic) Or for a jdbc connection a finalizer can remove a created table. And as all those data sources are available in the mover it's easier to start a pod that should quickly execute a delete action on a data store.

**Comment by roee88** [comment]
So short-term we need to do cleanup in our own code correctly and add a warning in the movement API comments (to appear in the generated docs). How about deleting the blueprint and only upon its actual deletion delete the namespace? Or do we have to delete the individual BatchTransfers?

Long term I think that we need to find an alternative design pattern, though it might be a difficult task.

**Comment by shlomitk1** [comment]
M4DApplication owns two resources: Blueprint and Namespace. It can delete Blueprint first, verify that Blueprint is deleted, and only then delete the namespace. Blueprint uninstalls helm charts and dies. This is not enough. Prior to uninstalling a release, it should "remember" the list of associated resources (it already manages them for status updates), and after uninstall - wait till all are deleted, and only then remove the finalizer and die. By waiting I refer to requeue every X seconds.

**Comment by roee88** [comment]
> Prior to uninstalling a release, it should "remember" the list of associated resources (it already manages them for status updates), and after uninstall - wait till all are deleted

No option to uninstall with a wait? Not saying that it's better, just checking the options.

**Comment by shlomitk1** [comment]
I did not think about that... It's definitely worth checking.
