### ISSUE TITLE
Copy modules receive arguments in a wrong format

### ISSUE THREAD

**Issue by shlomitk1** [IBM/the-mesh-for-data#111]
Helm releases of modules use Values generated by a Blueprint controller. The values can contain read/copy/write arguments. For example, the arrow-flight module refers to Values.read.source in order to get a data store for the source. 
Copy modules work directly with the `copy` sub-structure instead of the structure itself. 
For consistency, all occurrences of `.Values.destination` should be replaced with `.Values.copy.destination`. Same goes for `.Values.source` and `.Values.transformations`
Once the replacement is done, the special processing in manager for passing values to copy modules can be removed.

**Comment by roee88** [comment]
Documentation and code should match the following:

Context | Name | Type | Description
--------|------|------|------------
Root | name | String | Instance name
Root | namespace | String | Instance namespace
Root | labels | String[] | Instance labels
Root | copy | Copy | Copy arguments (optional)
Copy | source | [DataStore](https://ibm.github.io/the-mesh-for-data/docs/reference/api/generated/app/#k8s-api-github-com-ibm-the-mesh-for-data-manager-apis-app-v1alpha1-datastore) | Copy source 
Copy | destination | [DataStore](https://ibm.github.io/the-mesh-for-data/docs/reference/api/generated/app/#k8s-api-github-com-ibm-the-mesh-for-data-manager-apis-app-v1alpha1-datastore)| Copy sink
Copy | actions | [EnforcementAction](https://ibm.github.io/the-mesh-for-data/docs/reference/api/generated/connectors.pb/#EnforcementAction)[] | Actions on copy
Root | read | Read[] | Read arguments (optional)
Read | source | [DataStore](https://ibm.github.io/the-mesh-for-data/docs/reference/api/generated/app/#k8s-api-github-com-ibm-the-mesh-for-data-manager-apis-app-v1alpha1-datastore) | Read datastore
Read | actions |  [EnforcementAction](https://ibm.github.io/the-mesh-for-data/docs/reference/api/generated/connectors.pb/#EnforcementAction)[]      | Actions for read item
Root | write | Write[] | Write arguments (optional)
Write | destination | [DataStore](https://ibm.github.io/the-mesh-for-data/docs/reference/api/generated/app/#k8s-api-github-com-ibm-the-mesh-for-data-manager-apis-app-v1alpha1-datastore) | Write datastore
Write | actions | [EnforcementAction](https://ibm.github.io/the-mesh-for-data/docs/reference/api/generated/connectors.pb/#EnforcementAction)[] | Actions on write item


@shlomitk1 please correct me if I missed something

**Comment by shlomitk1** [comment]
@roee88 We have `transformations `instead of `actions`
In addition, `assetID` string in `Read`

**Comment by shlomitk1** [comment]
Fixed by https://github.com/IBM/the-mesh-for-data/pull/112
