### ISSUE TITLE
Enable setting values for modules at registration time

### ISSUE THREAD

**Issue by roee88** [IBM/the-mesh-for-data#12]
A `M4DModule` resource can currently refer to a helm chart but without the ability to override default values. The assumption was that the `manager` will set all values. However, unlike data/governance related values that must be set by the `manager`, other values (such as the container image to use) can be specified in the  `M4DModule` resource.

The logic must ensure that a value from the manager must take affect when there is a conflict with a value from the  `M4DModule` resource.

**Comment by hunchback** [comment]
@roee88 so do you want something like this in the M4DModule yaml?

```
  chart: ghcr.io/the-mesh-for-data/m4d-db2wh:latest
  values:
    image.name: ghcr.io/the-mesh-for-data/mover:latest
```

**Comment by roee88** [comment]
This sounds reasonable to me
