### ISSUE TITLE
Kubeflow sample: M4DApplication returns a failure status

### ISSUE THREAD

**Issue by shlomitk1** [IBM/the-mesh-for-data#122]
Problem: the kubeflow sample is no longer working. The reason is that Egeria connector returns "geo not supported yet" instead of the data location. Since transformations need to be made, manager requires a copy to the processing geography. No copy modules are installed in the sample (no buckets exist either), thus no blueprint is created.
Solution: add “geo” in fullPath field in https://github.com/IBM/the-mesh-for-data/blob/master/third_party/egeria/usage/example_transactions.csv.json#L5 and it will “automatically” appear in qualifiedName  in https://github.com/IBM/the-mesh-for-data/blob/master/connectors/egeria/src/main/resources/json/asset/asset_metadata.json#L42. Then the string will be parsed by egeria-connector, and the "geo" field will be passed to manager. 
Requires changes to egeria-connector, kubeflow sample documentation.

**Comment by ronenkat** [comment]
@shlomitk1 why should it impact the kubeflow documentation? I assume we will put ```geo: default``` or something similar.

**Comment by shlomitk1** [comment]
> 
> 
> @shlomitk1 why should it impact the kubeflow documentation? I assume we will put `geo: default` or something similar.

I meant the sample json that is mentioned in the documentation. It should be updated with the new field.
