### ISSUE TITLE
Multicluster blueprint generation

### ISSUE THREAD

**Issue by roee88** [IBM/the-mesh-for-data#135]
|   |   |
| - | - |
| Design doc | https://ibm.box.com/s/62xh8iwu64aas4awb2fwtad8betn1e07 |
| Parent issue | #134 |
| Required issues | # |

# Description

The M4DAppliction controller currently creates a blueprint that spans a single cluster. This issue is to address the changes required to support managing blueprints in multiple clusters. Taking the separation of concerns approach, this shouldn't include orchestration logic. 

# Requirements

1. Create a single description of a blueprint that spans multiple clusters 
    - An auditable structure 
    - Describes desired state in all clusters
    - Not necessarily a CRD or persisted anywhere, though it can be if that is what will be decided
    - Future: would also be useful for picking an optimal blueprint from multiple choices, may be used to describe a cross-cluster data plane graph, etc.
1. Generation is based on:
    1. Input from the various connectors in the control plane (primary cluster)
    1. Registered M4DModules in the control plane (primary cluster)
    1. Registered remote clusters and the metadata of them: geo-location, cluster features (to check if a M4DModule is applicable in the cluster) - _current assumption: all modules installed in all clusters_
1. Generation is triggered by:
    1. A change in M4DApplication spec
    1. Once every X minutes to account for policy changes (future)
1. Keep track of actual state to reflect reconcile status
1. Efficiency
    1. No blueprint generation triggers other than what is listed here
    1. No operation if no changes to desired state are required
    1. Complete reconciliation as fast as possible (e.g., allow remotes to reconcile in parallel to each other)

**Comment by roee88** [comment]
@shlomitk1 can this be closed now?

**Comment by shlomitk1** [comment]
Closing.
