### ISSUE TITLE
Multicluster blueprint orchestration

### ISSUE THREAD

**Issue by roee88** [IBM/the-mesh-for-data#136]
|   |   |
| - | - |
| Design doc | [link] |
| Parent issue | #134 |
| Required issues | # |

# Description

The M4DAppliction controller currently creates a Blueprint that spans a single cluster. This issue is to address the changes required to support managing blueprints in multiple clusters. Taking the separation of concerns approach, this issue describes a control plane component (can even be just a go package) that handles orchestration logic. It shouldn't include logic for blueprint generation.

# Requirements

1. The input is a description of a multicluster blueprint
1. Using [Razee](https://razee.io/)
1. Create/Update/Delete in a remote cluster
1. Monitor status as updated by a remote cluster
1. The resources sent to remotes describe a blueprint rather than individual modules (Razee does not support deploying Helm charts)

**Comment by roee88** [comment]
The implementation can either directly use Razee or use an abstraction layer for CRUD-like operations on remote resources. For such an abstraction, if desired, a separate issue should be opened (and added to the "Required issues" list in the header of this issue). I would personally go with something that directly uses Razee first and only later try to generalize, otherwise we may fall into performance pitfalls. We can start a discussion about it here.

**Comment by roee88** [comment]
Following the existing codebase, namespace creation is also needed. The recommendations we got:
1. Watch Blueprints by type rather than using a label
2. Use a list of resources to create namespace+blueprint, need to validate first that namespace creation is synchronous in k8w api.

**Comment by roee88** [comment]
@tomersolomon1 @froesef can you please list what's missing in the current implementation?

**Comment by froesef** [comment]
After the latest change to a single namespace which is m4d-blueprints the deletion of blueprints works as expected. Closing..
