### ISSUE TITLE
Multicluster: kind setup

### ISSUE THREAD

**Issue by froesef** [IBM/the-mesh-for-data#141]
Extend the kind setup to allow for two clusters. One control cluster and one second that simulates a remote cluster. 
The registry should be shared with the two clusters so that both clusters can access it.

**Comment by roee88** [comment]
@froesef this should have been closed by https://github.com/IBM/the-mesh-for-data/pull/142 right?

**Comment by roee88** [comment]
Assuming yes, @froesef please reopen if not.
