### ISSUE TITLE
Cluster Identifier

### ISSUE THREAD

**Issue by simanadler** [IBM/the-mesh-for-data#145]
|   |   |
| - | - |
| Design doc | https://ibm.box.com/s/62xh8iwu64aas4awb2fwtad8betn1e07 |
| Parent issue | #144  |
| Required issues | # |

# Description

In a multi-cluster environment it is necessary to have a unique identifier for each cluster.  Need to determine what will be used.  

# Requirements

1. Determine what will be used for the unique identifier of each cluster in the multi-cluster environment
2. Determine if a user readable display name is also required

**Comment by roee88** [comment]
@froesef @tomersolomon1 is cluster name guaranteed to be unique?

**Comment by roee88** [comment]
Cluster name is unique within an organization. Already implemented.
