### ISSUE TITLE
movement controller: remove cmd and build folders

### ISSUE THREAD

**Issue by roee88** [IBM/the-mesh-for-data#151]
The top level cmd and build folders are only used for testing the movement controller, which makes the project structure confusing.

# Option 1: simple merge to other folders

Something like:
- [ ] Remove `Dockerfile.movement-controller` that is a duplicate of `manager/Dockerfile` 
- [ ] Move `Dockerfile.dummy-mover` to `test`
- [ ] Integrate Makefile with `manager/Makefile` and `Makefile` while removing duplications (only needs `movement-controller` target that go builds it and a target for dummy mover)
- [ ] Remove the `build` folder
- [ ] Move `movement-controller/main.go` to `manager` or a subfolder within
- [ ] Remove `cmd` folder

# Option 2: optional controllers using program arguments

Change main.go in manager to only start controllers (and related logic) if a flag is on. This way the same binary can be used to run just the movement controller. The dummy should still probably be part of test. Overlay for deploying just movement is needed. 

# Option 3: Plan for a future usage of build and cmd

Keep as is but create a readme that explains why it's there. Probably need to use just one way to run movement controller and if it's a separate binary then stick to it.

**Comment by froesef** [comment]
I propose to go with option 2. To use only one binary and enable controllers via flags. Here are the flags that I propose:

- enable-application-controller
- enable-blueprint-controller
- enable-motion-controller
- enable-all-controllers

The last flag would be the option that we currently have and would be set in the default deployment. This can be overwritten. By default all flags would be false.
