### ISSUE TITLE
Developer Documentation for Creating New Modules

### ISSUE THREAD

**Issue by simanadler** [IBM/the-mesh-for-data#156]
Document what needs to be done to create a new module that can be used by the mesh for data.

If someone is creating a new module (ex: data quality, transforms, …) it would be helpful to have instructions what components have to be provided, which go in the m4d repository, which are external.  For those that go in m4d indications of where to put the different components that need to be provided - module yaml, helm charts, tests, example ….

**Comment by JohnWesleyK** [comment]
Hey @simanadler, I'd like to work on this, can you please tell me how can I get started

**Comment by roee88** [comment]
I suggest that I will write something initial to replace the current text in https://ibm.github.io/the-mesh-for-data/docs/overview/modules/ and then we can pinpoint specific items that should be addressed in this text so someone could do a follow-up (e.g., by learning from the flight module).

**Comment by simanadler** [comment]
> I suggest that I will write something initial to replace the current text in https://ibm.github.io/the-mesh-for-data/docs/overview/modules/ and then we can pinpoint specific items that should be addressed in this text so someone could do a follow-up (e.g., by learning from the flight module).

@roee88 Not sure we need to replace this text.  It's a good general overview about modules.  However, in the contributing section we need something more detailed about how to create a module from a developer perspective.  I will try to start something.

**Comment by simanadler** [comment]
**Please confirm / answer question @roee88 @hunchback @froesef **
Based on the current code base.  If I as a developer want to create a new module called "newmoduleX", I have to do the following.  
(1) Create newmoduleX.yaml in https://github.com/IBM/the-mesh-for-data/tree/master/manager/testdata/e2e.  
This is applied to m4d-system _as part of which script?_
(2) Create a new folder newmoduleX under https://github.com/IBM/the-mesh-for-data/tree/master/modules.  
This can be done by copying https://github.com/IBM/the-mesh-for-data/tree/master/modules/m4d-template.
_Or is there something that generates this folder?_
(3) Create the module template - https://github.com/IBM/the-mesh-for-data/tree/master/modules/newmoduleX/templates/newModuleX.yaml.  This describes the parameters and from where they are taken.
(4) Create the module values template - https://github.com/IBM/the-mesh-for-data/blob/master/modules/newmoduleX/values.yaml
(5) Update the makefile with the name of the new module - https://github.com/IBM/the-mesh-for-data/blob/master/modules/newmoduleX/Makefile
(6) Update https://github.com/IBM/the-mesh-for-data/blob/master/modules/newmoduleX/Chart.yaml
(7) Update https://github.com/IBM/the-mesh-for-data/blob/master/modules/newmoduleX/templates/NOTES.txt
(8) Update https://github.com/IBM/the-mesh-for-data/blob/master/modules/newmoduleX/templates/_helpers.tpl

**Comment by roee88** [comment]
I consider all modules we have in `/modules` as being in a "bad shape". None of them is exposed to users yet by the way, hence why we don't put module.yaml outside of testing. I can later open a separate issue to describe it better.

I also think that targeting out of tree modules would be better at this point. Please consider it.

**Comment by roee88** [comment]
Closed by https://github.com/IBM/the-mesh-for-data/pull/172
