### ISSUE TITLE
quickstart: failing with old dependencies

### ISSUE THREAD

**Issue by hunchback** [IBM/the-mesh-for-data#161]
When running the current quickstart procedure, it does not specify the go v1.13 dependency,

```
[root@thinkers-inf the-mesh-for-data]# make install-tools
GOBIN=/root/the-mesh-for-data/./hack/tools/bin GO111MODULE=on go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.3.0
package sigs.k8s.io/controller-tools/cmd/controller-gen@v0.3.0: cannot find package "sigs.k8s.io/controller-tools/cmd/controller-gen@v0.3.0" in any of:
	/usr/lib/golang/src/sigs.k8s.io/controller-tools/cmd/controller-gen@v0.3.0 (from $GOROOT)
	/root/go/src/sigs.k8s.io/controller-tools/cmd/controller-gen@v0.3.0 (from $GOPATH)
make: *** [hack/tools/bin/controller-gen] Error 1
[root@thinkers-inf the-mesh-for-data]# 
```

Plus it make use of the kubectl which is installed on the host rather than using the verified version which is installed as part of the tools that the-mesh-for-data installs, notice here it is using a very old version deployed on the host:

```
[root@thinkers-inf bin]# kubectl version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"a02f27a", GitTreeState:"clean", BuildDate:"2020-04-13T12:04:13Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
[ro
```

**Comment by roee88** [comment]
I still don't get it. The quick start is not for developers. It's for users. If a minimum version of kubectl is required just state it. The user should not install the tools (eventually he would only need to apply yamls or something), we temporarily reused specific make targets to perform installation, but which of them actually required any tool?

**Comment by shlomitk1** [comment]
Missing: helm prerequisites. A user has installed a wrong version of Helm which caused a problem with vault installation.
