### ISSUE TITLE
Replace Egeria lab with a different catalog

### ISSUE THREAD

**Issue by roee88** [IBM/the-mesh-for-data#163]
Egeria lab is not suitable as an entry point catalog. The installation is difficult (as reported by several users #162) and the basic experience turned out to be lacking. 

I would like to consider using a different catalog to showcase the M4D project. The options are to pick an existing open source data catalog or to write our own basic catalog that will also demonstrate our minimal requirements from a data catalog.

I'm currently examining both options with concrete plans to:
1. Experiment with  https://marquezproject.github.io/marquez/ and https://www.amundsen.io/amundsen/
2. Design a basic catalog and estimate how much efforts it would be to implement it

Input from people who did similar evaluations would be helpful 

cc @rohithdv

**Comment by simanadler** [comment]
> I'm currently examining both options with concrete plans to:
> 
>     1. Experiment with  https://marquezproject.github.io/marquez/ and https://www.amundsen.io/amundsen/
> 
@roee88 I believe that @etykha and @rohithdv did a search for open source data catalogs and I believe they experimented with both of these options.

**Comment by roee88** [comment]
@rohithdv please share

**Comment by rohithdv** [comment]
Yes we had explored Amundsen earlier along with Ety and Rishi. I could fish out the following docs from our chats earlier. 

Initial comparison table between Amundsen and Egeria (created by Ety),
https://ibm.ent.box.com/notes/692966717227

Lyft/Amundsen
Quick Start guide: https://github.com/lyft/amundsen/blob/master/docs/installation.md#bootstrap-a-default-version-of-amundsen-using-docker

Document created by Rishi Saket on using Amundsen: 

[Amundsen Exploration.zip](https://github.com/IBM/the-mesh-for-data/files/5597287/Amundsen.Exploration.zip)

@roee88 @simanadler

**Comment by rohithdv** [comment]
Basically the summary of our findings was Amundsen is more powerful than Egeria with respect to support for connectors to different datasources. But we went with Egeria as it was IBM supported project.

Amundsen is also featured in number of blogs like [this one which I found interesting](https://eugeneyan.com/writing/data-discovery-platforms/?utm_campaign=Data_Elixir&utm_source=Data_Elixir_310)

As for Marquez, we have not explored it earlier. It looks promising at a first look. Thanks.

**Comment by roee88** [comment]
An alternative suggested by @rohithdv is to build a simple asset catalog with Egeria: https://egeria.odpi.org/open-metadata-publication/website/cataloging-assets/. @rohithdv will contact an Egeria community member for a discussion.

**Comment by elsalant** [comment]
Can we use OPA as a lightweight catalog, and just supply additional policies to return the catalog selection?

**Comment by simanadler** [comment]
> Can we use OPA as a lightweight catalog, and just supply additional policies to return the catalog selection?

OPA isn't a catalog.  It's a policy engine.

**Comment by elsalant** [comment]
> > Can we use OPA as a lightweight catalog, and just supply additional policies to return the catalog selection?
> 
> OPA isn't a catalog. It's a policy engine.

Yes, I understand this, but it seems to me that just as we have user roles and access privileges stored in OPA we could have module names or whatever in OPA.  Maybe I am missing something, but is there a difference between getting a list of redaction policies back for a given condition, and getting a list of modules back for a given configuration requirement? Again, I am talking about a lightweight implementation of a catalog for testing purposes as is being discussed in this thread and say for demonstrating in EU projects or whatever.

**Comment by roee88** [comment]
I didn't mean that we target fixed value, but I still agree that OPA is a valid option for our needs.

**Comment by elsalant** [comment]
Yes, this is just a simple example.  Conceptually, it means using the data (JSON) to hold what would be catalog information (and is easily updatable via a REST command to the OPA server) and the rego engine to make the appropriate selection from JSON values.

**Comment by roee88** [comment]
I'm looking at a replacement using OPA together with @elsalant. This will be in parallel to the Egeria thread.

**Comment by roee88** [comment]
Closing. @rohithdv @ritwikc please open a discussion for the Egeria thread.
