### ISSUE TITLE
Helm chart resources are not created in an intended workspace

### ISSUE THREAD

**Issue by shlomitk1** [IBM/the-mesh-for-data#17]
When helm is applied from command line with an option --namespace, the behavior is correct: all resources are allocated in the specified namespace. For example:
`/hack/tools/bin/helm upgrade --no-hooks --install test --namespace xxx --values values.yaml .`

When pkg/helm.go functions are invoked in `applyChartResource` of Blueprint reconciler, the resources are allocated in the current namespace, although the correct namespace name is passed to the install/upgrade methods of the helm package.
A hack is to specify namespace for each resource using` namespace: {{ .Values.metadata.namespace }}`

**Comment by roee88** [comment]
I ran the `TestHelmRelease` test against a different namespace than the current one in context (changed `kubeNamespace`) and it did create the chart in the right namespace (the one set in `kubeNamespace` and passed to Install and not the current namespace). So this functions seems to be working properly. 

Have you debugged applyChartResource and observed that the right namespace is passed to `Helmer.Install`? I need more details.

**Comment by shlomitk1** [comment]
Yes, this is exactly the problem. Chart is created in the correct namespace, the actual resources are not.
When current namespace is m4d-system and the specified namespace is m4d-cwd6t, I get the resources in m4d-system and the chart in m4d-cwd6t. By resources I mean service + deployment + configMap + serviceAccount yamls.
```
helm list --namespace=m4d-cwd6t
NAME                 	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                    	APP VERSION
r417b5910533125d0e4f1	m4d-cwd6t	4       	2020-09-23 10:50:03.958106485 +0000 UTC	deployed	arrow-flight-module-0.0.1	1.0     
```

I've checked that **install.Namespace** is correct (see the function below).
```
func (r *Impl) Install(chart *chart.Chart, kubeNamespace string, releaseName string, vals map[string]interface{}) (*release.Release, error) {
	cfg, err := getConfig(kubeNamespace)
	if err != nil {
		return nil, err
	}
	install := action.NewInstall(cfg)
	install.ReleaseName = releaseName
	install.Namespace = kubeNamespace
	return install.Run(chart, vals)
}
```

**Comment by roee88** [comment]
I see. The problem is in pkg/helm. It uses https://github.com/helm/helm/blob/b0fdb5461fbc7e1b52f61613d3e7a22d85c7a794/pkg/cli/environment.go#L178 which targets the current namespace.

**Comment by shlomitk1** [comment]
Yes, this is exactly the problem. Chart is created in the correct namespace, the actual resources are not.
When current namespace is m4d-system and the specified namespace is m4d-cwd6t, I get the resources in m4d-system and the chart in m4d-cwd6t. By resources I mean service + deployment + configMap + serviceAccount yamls.
```
helm list --namespace=m4d-cwd6t
NAME                 	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                    	APP VERSION
r417b5910533125d0e4f1	m4d-cwd6t	4       	2020-09-23 10:50:03.958106485 +0000 UTC	deployed	arrow-flight-module-0.0.1	1.0     
```

I've checked that **install.Namespace** is correct (see the function below).
```
func (r *Impl) Install(chart *chart.Chart, kubeNamespace string, releaseName string, vals map[string]interface{}) (*release.Release, error) {
	cfg, err := getConfig(kubeNamespace)
	if err != nil {
		return nil, err
	}
	install := action.NewInstall(cfg)
	install.ReleaseName = releaseName
	install.Namespace = kubeNamespace
	return install.Run(chart, vals)
}
```

**Comment by shlomitk1** [comment]
I don't really understand how the command call with --namespace works fine - do they set the config in a different way?

**Comment by roee88** [comment]
The flag just overrides the default. See https://github.com/helm/helm/blob/b0fdb5461fbc7e1b52f61613d3e7a22d85c7a794/pkg/cli/environment.go#L102. I don't see a programmatic way to set it so we should probably avoid using pkg/cli and just set the ConfigFlags directly.
