### ISSUE TITLE
helm3 packaging for m4d

### ISSUE THREAD

**Issue by hunchback** [IBM/the-mesh-for-data#184]
# Overview

To help simplify deployment of the-mesh-for-data we want the entire core (including connectors) to have a helm based deployment (optionally moving CRD into a separate deployment).

# Stage 0: Helm Chart: manager CRDs

the reason for have a separate helm chart for CRDs is:

- we may have several helm charts which depend on the CRDs requiring it be deployed independently
- we want to be able to upgrade the CRDs independently from core
- that this is an acceptable practice see rancher/fleet for example

so the result would be supporting:

```
helm install -g m4d-crd
```

This is how Rancher Fleet works: https://github.com/rancher/fleet/tree/master/charts/fleet-crd

And is defined as a plausible option (Method 2) here: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/

# Stage 1: Helm Chart:  manager

The idea is to replace the current kustomize based manager deployment with a helm chart wrapper which enables to configure where the helm modules and module images are downloaded from (the docker registry location).

# Stage 2: Helm Chart: manager + connectors

Next we add connectors to the deployment: 
- opa-connector
- vault-connector
- egeria-connector (or egeria replacement)

Replacing their current `bash` based deployment with extending the helm chart, and exposing configuration of: the service endpoints (and credentials) needed for the connectors to connect.

This work _may_ also include merging the code into the manager as library code (currently the manager communicates to each connector which exposes the service at a designated port number)

# Stage 3: Helm chart: manager + connectors + 3rd-party

In small (to evaluation/demo) deployments you may want to deploy _some_ of the 3rd party tools, thus the proposal is to add these as configurable options such that one can either deploy m4d with a local/private instance of a required 3rd party of rather point to an existing shared 3rd party

specifically we should consider:
- vault server
- cert-manager server
- TBD

# Stage 4: Helm chart: manager + connectors + 3rd-party + modules

The current system of module management was intended to enable external parties to extend m4d w/o having to change the core of m4d, this approach makes sense for either super-large-and-complex OSS (which m4d is not, as the lines-of-code its 1/100 or 1/1000 or projects such as envoy, k8s, istio and others), or it was suppose to serve for extending a closed source project (which again is not the case of m4d).

So the proposal is to eliminate all together the module notion, merge it into the core of m4d and have it all managed via a single helm chart.

# Stage 5: make architecture multi-cluster compatible/agnostic

to be agnostic to multi-cluster tool one should have deployment options which enable to setup each cluster mostly independant from others such as:

- manager cluster: this is the cluster that the end-user works such as via a Jupiter Notebook (possibly as part of KubeFlow), in this location the user has access to local instances of remote data-sources ... so here we would have a M4DApplication 
- agent (or data source) cluster: this could be a branch office which is the owner the a data set which includes PI fields which have to be obfuscated or redacted before is can be shared with the manager ... so here we would need a new kind such as M4DApplicationDatasource

by this separation we now can deploy to each cluster totally independently such that the M4DApplication and the M4DApplicationDatasource can be pushed directly into the GitOps source feeding the multi-cluster solution (with labels per cluster defining what is deployment where). by doing this we would eliminate the plutter and its' integration with Razee API. 

# Supporting propriety extensions

WKC code which can't be released can still be supported to using an internal fork for m4d and then extending the code with the WKC connector capabilities. That said it is still recommended to revisit the WKC connector and consider reimplementation w/o the IP restrictions in the current implementation.

**Comment by roee88** [comment]
> Stage 1: Helm Chart: manager (including CRDs)

Agreed. 

> Stage 2: Helm Chart: manager + connectors

I would have a single Helm chart for all connectors following the idea of a "stack" presented in https://github.com/IBM/the-mesh-for-data/issues/182 and keep it separate from the manager helm chart. I would wait with this one until we settle on #182.

> Stage 3: Helm chart: manager + connectors + 3rd-party

I don't think that it's a good idea to vendor a helm chart for cert-manager (Vault already has a Helm chart btw but we don't use it yet). 

> The current system of module management was intended to enable external parties to extend m4d w/o having to change the core of m4d

A module implements a data-centric function to implement a policy action. This is completely separate from M4D control plane and must be extendible. We are definitely not planning to remove modules but feel free to raise this in the next community meeting for a broader discussion.

> Supporting propriety extensions

I don't think that suggesting to fork the project is a good idea. Again, this should probably be discussed in a community meeting rather than an issue.

**Comment by roee88** [comment]
I think it would be good to open a separate issue for Stage 1.

**Comment by shlomitk1** [comment]
> This work may also include merging the code into the manager as library code (currently the manager communicates to each connector which exposes the service at a designated port number)

I don't understand how this can be done. There may be any number of catalog connectors, for example, while only one is configured for a specific deployment. We already have a policy manager merged as a library. The policy manager does not serve as a connector, though, but rather like a "connector manager" that is configured to work with a specific connector.

> So the proposal is to eliminate all together the module notion, merge it into the core of m4d and have it all managed via a single helm chart.

Suppose an administrator wants to deploy only a subset of the modules. I don't see a way to manage this the way you propose.

**Comment by ronenkat** [comment]
@hunchback deployment should support the architecture, not the other way around.
Lets start with the 1st stage -- it is a very good idea.
We should keep the architecture concepts and a pluggable design. Specifically, connectors should not be part of the manager code, they need to be seperate, and we do envision out of tree connectors and modules

**Comment by hunchback** [comment]
> @roee88 : I would have a single Helm chart for all connectors following the idea of a "stack" presented in #182 and keep it separate from the manager helm chart. I would wait with this one until we settle on #182.

the idea behind the single helm (which includes in it the default or should I say `static` connectors) is that it provides the desired user experience, for example the Linux kernel has many extensions to the core is the form of modules but by default many of these modules are statically compiled into the kernel and deployed in the RPM which includes the kernel core.

this simplicity is vital for the success of any project but more so for an OSS which does not assume pain support.

**Comment by hunchback** [comment]
>> Stage 3: Helm chart: manager + connectors + 3rd-party
> @roee88: I don't think that it's a good idea to vendor a helm chart for cert-manager (Vault already has a Helm chart btw but we don't use it yet).

the idea is to include a minimal local cert-manager used only by m4d, this is commonly used in other projects (with the aim of simplification):
- kubernetes installs an internal 

- skydive installs an internal ElasticSearch (https://github.com/skydive-project/skydive-helm/blob/master/values.yaml#L51)

**Comment by hunchback** [comment]
>> The current system of module management was intended to enable external parties to extend m4d w/o having to change the core of m4d

> @roee88 A module implements a data-centric function to implement a policy action. This is completely separate from M4D control plane and must be extendible. We are definitely not planning to remove modules but feel free to raise this in the next community meeting for a broader discussion.

a module has no independent role and requires m4d the fact that it is data centric be it flight-arrow, kafka, s3 does not in itself justify having is separated out of m4d, for example rancher is a huge project which integrates with many cert manager systems but the code for integrating (and even deployment of the internal services) are all part of the single rancher helm chart:(https://github.com/rancher/rancher/tree/master/chart )

now rancher is a project 100x larger and more complex than m4d (it is also highly popular and successful) so I am sure we can learn from that ...

**Comment by hunchback** [comment]
>> Supporting propriety extensions

> @roee88: I don't think that suggesting to fork the project is a good idea. Again, this should probably be discussed in a community meeting rather than an issue.

its' a reasonable option, a better option would be to think very carefully before implementing propriety code for m4d, specifically the WKC could be re-implemented as OSS, in any case the decision to write propriety extensions is also expensive in term of life-cycle-management and thus should be chosen light heartedly.

**Comment by hunchback** [comment]
> @roee88: I think it would be good to open a separate issue for Stage 1.
> @ronenkat: Lets start with the 1st stage -- it is a very good idea.

**Comment by roee88** [comment]
Comments burst.

1. S1: good 👍
1. S2: we can always create a separate chart and then if we decide to we can include it as an optional dependency to the S1 chart. Not a big deal.
1. S3: You can't "privately" install a cluster wide dependency... Rancher here is a bad example given the context. Always consider the context and not just how big and wonderful a project is... Read the Warning in https://cert-manager.io/docs/installation/kubernetes/ please. Again, optional chart dependencies are a good option to consider here.
1. S4: modules are actually associated with connectors more than with to the core project. We can chat on a github issue for days but this is just something that we disagree about. Again feel free to raise this in a community meeting instead.

**Comment by hunchback** [comment]
>> So the proposal is to eliminate all together the module notion, merge it into the core of m4d and have it all managed via a single helm chart.

> @shlomitk1 Suppose an administrator wants to deploy only a subset of the modules. I don't see a way to manage this the way you propose.

why would an administrator actually care about if more modules that what he is using are deployed? do you care that you laptop OS has drives for devices you don't use (and it must have hundreds of such drivers) ... you don't.

and if there is  a really good reason not to deploy all modules then you can simply add a parameter to the helm values to not deploy that module (which then again in most cases this is an overkill)

**Comment by hunchback** [comment]
>> This work may also include merging the code into the manager as library code (currently the manager communicates to each connector which exposes the service at a designated port number)

> @shlomitk1 I don't understand how this can be done. There may be any number of catalog connectors, for example, while only one is configured for a specific deployment. We already have a policy manager merged as a library. The policy manager does not serve as a connector, though, but rather like a "connector manager" that is configured to work with a specific 
connector.

but why can't the connectors be merged as libraries - called via API rather than over a socket?

**Comment by hunchback** [comment]
> Comments burst.
> 
> 1. S1: good 👍
> 2. S2: we can always create a separate chart and then if we decide to we can include it as an optional dependency to the S1 chart. Not a big deal.
> 3. S3: You can't "privately" install a cluster wide dependency... Rancher here is a bad example given the context. Always consider the context and not just how big and wonderful a project is... Read the Warning in https://cert-manager.io/docs/installation/kubernetes/ please. Again, optional chart dependencies are a good option to consider here.
> 4. S4: modules are actually associated with connectors more than with to the core project. We can chat on a github issue for days but this is just something that we disagree about. Again feel free to raise this in a community meeting instead.

will start with s1 ...

**Comment by hunchback** [comment]
> @ronenkat We should keep the architecture concepts and a pluggable design. Specifically, connectors should not be part of the manager code, they need to be seperate, and we do envision out of tree connectors and modules

this is a claim a challenge post the demo would be happy to open up this topic in the OSS weekly with my main grievance being: 

1. this break up makes not only deployment much more complex but also life-cycle-management including upgrades
2. this break up makes implementation of multi-cluster much more complex, thus as in our case forcing us to implement multi-cluster features (the the plotter effectively defines the per cluster blueprint) with the cost being that rather than being multi-cluster tool agnostic (with zero integration effort per tool) we rather require heavy integration effort per each tool (so if we replace Razee with Fleet we need to invest more effort).
3. the current pluggable architecture is a classical closed source software resulting architecture in which one has to provide means for extention assuming the core is not accessible to the 3rd party ... in OSS the dynamics are different on the contrary one wants to get 3rd party contributors to join the project and extend it (starting with a specific domain such as a data-source of interest) but later moving to extend the core.

so addressing deployment exposed issues in the current architecture which should be revisited

-

**Comment by shlomitk1** [comment]
> but why can't the connectors be merged as libraries - called via API rather than over a socket?

Let's say we have three catalog connectors: c1, c2 and c3. 
Currently, manager will always contact one connector, using a configured service name/port.
If all are merged together, we will get three APIs instead of one, or three implementations of an interface. And if another connector is added, this will require to change the code. Unless I misunderstand something...

**Comment by shlomitk1** [comment]
> why would an administrator actually care about if more modules that what he is using are deployed? do you care that you laptop OS has drives for devices you don't use (and it must have hundreds of such drivers) ... you don't.
> 
> and if there is a really good reason not to deploy all modules then you can simply add a parameter to the helm values to not deploy that module (which then again in most cases this is an overkill)

Let's say there are two arrow-flight modules, one is propriety of org1, another - of org2. In org1 the admin will install one module, in org2 - another. Or any other considerations to replace one module by another that are not a part of manager decision or user input.

**Comment by hunchback** [comment]
> > why would an administrator actually care about if more modules that what he is using are deployed? do you care that you laptop OS has drives for devices you don't use (and it must have hundreds of such drivers) ... you don't.
> > and if there is a really good reason not to deploy all modules then you can simply add a parameter to the helm values to not deploy that module (which then again in most cases this is an overkill)
> 
> Let's say there are two arrow-flight modules, one is propriety of org1, another - of org2. In org1 the admin will install one module, in org2 - another. Or any other considerations to replace one module by another that are not a part of manager decision or user input.

in this case our architecture should support org1 and org2 by each of them being a separate deployment of m4d in a separate namespace (org1 and org2) and all deployment anyway needs to be managed by the multi-cluster gitops solution (and should not be bypassed manually)

**Comment by roee88** [comment]
So starting with stage 1, you suggested to have one chart for CRDs and one chart for the manager due to the caveats described in https://helm.sh/docs/chart_best_practices/custom_resource_definitions/. I will focus on the CRDs first then.

The CRDs are generated from source code using controller-gen in https://github.com/IBM/the-mesh-for-data/blob/58e7129225302ae7fb503d7d1018e42c63854ac2/manager/Makefile#L40. This currently dumps the CRDs to config/crd/bases as part of the kustomize layout. I assume that we want to keep the kustomize layout at least until we're done with stage 1. My question is how do you want to ensure that the crds chart contains the generated CRDs rather than a manual copy.

**Comment by hunchback** [comment]
closing as not relevant in current form (@roee88 please open alternative PR/PRs)
