### ISSUE TITLE
travis: tagging images as latest does not respect merge order

### ISSUE THREAD

**Issue by roee88** [IBM/the-mesh-for-data#212]
When two PRs are merged around the same time, the `latest` images are not guaranteed to reflect master (e.g., when the earlier merge runs the docker pushes later). It can even be mixed.

**Comment by hunchback** [comment]
@roee88 interesting a classical race condition which to solve properly would require to make the entire process (of updating the batch of docker images atomic):

1. either by using some form of sync between builds
2. or, by reducing m4d to use a single docker image :-)

**Comment by roee88** [comment]
I don't see how a single image solves it. Anyway, if you're unfamiliar with a way to solve this I can look around.

**Comment by roee88** [comment]
We're probably going to move to GitHub Actions anyway, then we should consider if adding a third party action from those listed in https://github.community/t/prevent-parallel-workflows/16370/21 is worth it.
