### ISSUE TITLE
Ingest Scenario Support

### ISSUE THREAD

**Issue by simanadler** [IBM/the-mesh-for-data#221]
Add support for copying data from an external system into the managed environment and ensuring it is cataloged in the data catalog.  There are several scenarios in which new data is created:
1) Data in external systems are ingested for the first time into the environment, and thus the new data set needs to be cataloged.
2) Data is being appended or is updating an existing data set, and thus the data set already exists in the catalog.  _Does classification need to be re-run after new data is added?  Does new metadata need to be added? _

For a discussion about the ingest flow implementation options and what was chosen: https://docs.google.com/document/d/1j5NBs-xN8y8hxM01g2ZwgGvROQGIV-yqk-LwbJsfUoo/edit?usp=sharing

For information about policies relating to these scenarios see: https://docs.google.com/document/d/1rQ4ykFfOZ4mfD6rrd1XgInKSiJ0DPBoHu9xwawJecFI/edit?usp=sharing

**Comment by roee88** [comment]
Why are these part of the same issue?

**Comment by roee88** [comment]
Focusing on ingest, my understanding is that you wanted a module to do the ingest copy. In that case, what I imagined is `M4DApplication` with the regular read parameters but with these changes/extensions: 
1. Support read not from a catalog (cf. creating a private catalog for the ingestion)
2. Adding usage hints/parameters like we discussed in https://github.com/IBM/the-mesh-for-data/issues/93 (useful for implicit copy as well)
3. Make the selector optional (once we add cluster selector it could also be used as an optional parameter)
4. Add the cataloging functionality

**Comment by simanadler** [comment]
@roee88 I put ingest and write in the same issue because I wanted to make sure we aligned the approach for both in order to not "break the architecture".  If you prefer to separate them that's fine.

As for the additions to M4DApplication, my thoughts were the same.  I am working on updating the M4DApplication yaml.  Would you like me to do a draft PR so it can be reviewed before additional work is done?

**Comment by roee88** [comment]
> @roee88 I put ingest and write in the same issue because I wanted to make sure we aligned the approach for both in order to not "break the architecture". If you prefer to separate them that's fine.

I think it would be more meaningful to separate these two. They require two very different changes.

> As for the additions to M4DApplication, my thoughts were the same. I am working on updating the M4DApplication yaml. Would you like me to do a draft PR so it can be reviewed before additional work is done?

Sure

**Comment by roee88** [comment]
While "ingest flow" is a use case, I kindly ask to treat it as a set of separate features not directly tied to ingest. There should be no "ingest" anything in the codebase at all (at least for the near future).

The set of features I extracted from your description is:
1. ~~Enable specifying datasets that are not in the catalog~~
1. Make the workload selector optional (I think @shlomit already implemented)
1. User preferences in M4DApplication (as described in #93, e.g.: columns, cron)
1. Enable registering in the catalog
1. Storage resource allocation
1. Refine policy model to read and write policies

I would like to remove the first item "Enable specifying datasets that are not in the catalog" from the list. This makes the definitions that we currently have hardcoded for connection types much more dominant and public and would make the work on taxonomy 10x harder. Instead, with some minor work the solution to #163 from me and Eliot would address the ingest use case as well. This will also remove the need to address #250. Let's sync first and then drop the details here.

Feel free to counter the list above with your own list and once we are in agreement we can open concrete issues and PRs that follow them. It will make getting things reviewed and merged much easier.

**Comment by simanadler** [comment]
> While "ingest flow" is a use case, I kindly ask to treat it as a set of separate features not directly tied to ingest. There should be no "ingest" anything in the codebase at all (at least for the near future).
> 
> The set of features I extracted from your description is:
> 
>     1. ~Enable specifying datasets that are not in the catalog~
> 
>     2. Make the workload selector optional (I think @shlomit already implemented)
> 
>     3. User preferences in M4DApplication (as described in #93, e.g.: columns, cron)
> 
>     4. Enable registering in the catalog
> 
>     5. Storage resource allocation
> 
>     6. Refine policy model to read and write policies
> 
> 
> I would like to remove the first item "Enable specifying datasets that are not in the catalog" from the list. This makes the definitions that we currently have hardcoded for connection types much more dominant and public and would make the work on taxonomy 10x harder. Instead, with some minor work the solution to #163 from me and Eliot would address the ingest use case as well. This will also remove the need to address #250. Let's sync first and then drop the details here.

Do I understand that you are  suggesting that we assume the data has been cataloged prior to ingest?  If so, I'm confused since importing data from external, transactional systems into the data lake and cataloging it is the main requirement of the ingest flow.  If that's not what you meant then I'm not clear on how we implement ingest without implementing item #1.  The user has to indicate somehow where the data is that he wants to ingest.  Let's sync.  :)
> 
> Feel free to counter the list above with your own list and once we are in agreement we can open concrete issues and PRs that follow them. It will make getting things reviewed and merged much easier.

**Comment by roee88** [comment]
Refined list:
1. Supporting multiple catalog connectors (w/ one to be used as a catalog for external datasets); the actual requirement here is multiple catalogs rather than multiple catalog connectors but not all catalog systems support "multiple catalogs".
2. Make the workload selector optional (I think @shlomit already implemented)
3. User preferences in M4DApplication (as described in #93, e.g.: columns, cron)
4. Enable registering in the catalog
5. Storage resource allocation
6. Refine policy model to read and write policies

The decision was to build upon implicit copy. That is, we **don't** treat it as an input asset and output asset and a `M4DApplication` that does the ingest on its own (which is something that we may want to move to in the future). 

My understanding is that two alternatives are considered:
1. For ingest the specification is of an input asset and output asset but **without** delegating the ingest logic to the workload.
2. For ingest the specification is of an input asset just like in implicit copy

I strongly push for option 2 and don't see how in option 1 the output specification (the must fit what we _will_ define for write) can be leveraged for copy that the manager does rather than the application. Suggestions are welcome, preferably in the form of a YAML example. 
 
What we already have today for implicit copy is that the user specifies in `M4DApplication` the input datasets and how he wants to consume them. The manager has its own logic (future: policy based #93) to decide if an implicit copy is needed and then the implicit copy flow follows. The main point of option 2 is to extend the manager logic to add a cataloging step to the existing flow.

We could have done something explicit in the spec about requiring a copy and other stuff we described in #93:
```yaml
spec:
  selector: ... 
  appInfo: ...
  data:
    - dataSetID: "{\"ServerName\":\"cocoMDS3\",\"AssetGuid\":\"ASSET_ID\"}"
      ifDetails: 
        protocol: m4d-arrow-flight
        dataformat: arrow
        copy:
           catalog: "catalog name to add the copied asset to"
           repeat: ...  
```

Instead, we currently went for something more implicit: if the requested asset is from a catalog not marked as the "main" catalog and the selector isn't for a specific workload then we catalog the copied asset. This is again something that we can change later following #93.

**Comment by roee88** [comment]
> Instead, we currently went for something more implicit: if the requested asset is from a catalog not marked as the "main" catalog and the selector isn't for a specific workload then we catalog the copied asset. Refinements and changes here are also welcome. Conceptually:

Given that in some cases there could be multiple catalog IDs in the same catalog system it might actually be better to take a more explicit approach.

**Comment by simanadler** [comment]
> Refined list (@sima please fix if wrong)
> 
>     1. Supporting multiple catalog connectors (w/ one to be used as a catalog for external datasets); the actual requirement here is multiple catalogs rather than multiple catalog connectors but not all catalog systems support "multiple catalogs".
> 
>     2. Make the workload selector optional (I think @shlomit already implemented)
> 
>     3. User preferences in M4DApplication (as described in #93, e.g.: columns, cron)
> 
>     4. Enable registering in the catalog
> 
>     5. Storage resource allocation
> 
>     6. Refine policy model to read and write policies
> 
> 
> The decision was to build upon implicit copy. That is, we **don't** treat it as an input asset and output asset and a `M4DApplication` that does the ingest on its own (which is something that we may want to move to in the future).
> 
> My understanding is that two alternatives are considered:
> 
>     1. For ingest the specification is of an input asset and output asset but **without** delegating the ingest logic to the workload.
> 
>     2. For ingest the specification is of an input asset just like in implicit copy
> 
> 
> I strongly push for option 2 and don't see how in option 1 the output specification (the must fit what we _will_ define for write) can be leveraged for copy that the manager does rather than the application. Suggestions are welcome, preferably in the form of a YAML example.
> 
> What we already have today for implicit copy is that the user specifies in `M4DApplication` the input datasets and how he wants to consume them. The manager has its own logic (future: policy based #93) to decide if an implicit copy is needed and then the implicit copy flow follows. The main point of option 2 is to extend the manager logic to add a cataloging step to the existing flow.
> 
> We could have done something explicit in the spec about requiring a copy and other stuff we described in #93:
> 
> ```yaml
> spec:
>   selector: ... 
>   appInfo: ...
>   data:
>     - dataSetID: "{\"ServerName\":\"cocoMDS3\",\"AssetGuid\":\"ASSET_ID\"}"
>       ifDetails: 
>         protocol: m4d-arrow-flight
>         dataformat: arrow
>         copy:
>            catalog: "catalog name to add the copied asset to"
>            repeat: ...  
> ```
> 
> Instead, we currently went for something more implicit: if the requested asset is from a catalog not marked as the "main" catalog and the selector isn't for a specific workload then we catalog the copied asset. 

It could be done the way you describe.  Currently the approach I was taking is the indication is if there is no user workload and the requested data set flow is COPY (rather than READ).  @roee88 Please let me know if you prefer your approach and I will change accordingly.

Refinements and changes here are also welcome. Conceptually:
> 
> ```yaml
> spec:
>   selector: ... # Omitted or just cluster selector
>   appInfo: ...
>   data:
>     - dataSetID: ... # of a non main catalog
         catalogID: ... # indicates the catalog to be used
         flow: .. # READ or COPY
>       ifDetails: 
>         protocol: m4d-arrow-flight
>         dataformat: arrow
> ```

**Comment by simanadler** [comment]
This image describes the flow for the ingest scenario.
<img width="815" alt="image" src="https://user-images.githubusercontent.com/11739268/104290394-f96d2380-54c2-11eb-902d-f7bc046a5ca3.png">

**Comment by simanadler** [comment]
This is my understanding of the ingest flow as per our various conversations: @ronenkat @roee88 @shlomitk1 

<img width="802" alt="image" src="https://user-images.githubusercontent.com/11739268/104292699-d42de480-54c5-11eb-9cf7-0e4e9c3a8df8.png">

**Comment by roee88** [comment]
@shlomitk1 @simanadler do we need this issue open?

**Comment by shlomitk1** [comment]
I think it can be closed.
