### ISSUE TITLE
multi-cluster architecture redesign

### ISSUE THREAD

**Issue by hunchback** [IBM/the-mesh-for-data#237]
the current multi-cluster architecture has many fundamental flaws:

1. it is tightly coupled to Razee (handled by the plotter controller)
2. it re-implements multi-cluster deployment decisions in m4d itself efectivly limiting deployment options (plotter spec specifies when to deploy each blueprint)
3. it creates a split in the execution path: uni-cluster uses vs. multi-cluster. instead of uni-cluster just being a sub-class of multi-cluster

the proposed architecture includes:
1. removing Plotter which is deployed in the master
2. introducing ApplicationResource to be deployed on each remote cluster or in the master in the case of uni-cluster

this will give us a seamless integration into any multi-cluster solution: Razee, Fleet included

**Comment by roee88** [comment]
Please elaborate on what `ApplicationResource` is

**Comment by shlomitk1** [comment]
1. Razee or Fleet is just an implementation detail which is hidden inside ClusterManager. Plotter controller is unaware of the implementation beneath. 
2. Deployment decisions are done by M4DApplication controller based on government policies, business logic, etc. 
3. A split in the execution path is temporal. Plotter will be generated for any cluster configuration.
I don't understand the flaws in the current architecture, nor the proposed architecture. Please explain.

**Comment by ronenkat** [comment]
I am closing this issue.
@shlomitk1 addressed how M4D handle observations (1) and (3).
I don't think (2) is an issue at this time, as we don't have a multi-cloud deployment manager that can include complex logic on the table.
@hunchback, if you believe further discussion is needed, lets of a discussion thread to discuss options.
