### ISSUE TITLE
API of PolicyManager does not cover write/ingest use-cases

### ISSUE THREAD

**Issue by shlomitk1** [IBM/the-mesh-for-data#250]
Related to https://github.com/IBM/the-mesh-for-data/issues/221

The input to PolicyManager is represented by the following structure:
```
message ApplicationContext {
    string app_id = 1;                // string that identifies the application (namespace + appID) that will be used against secretProvider to obtain the realted credetnials
    ApplicationDetails app_info = 2;
    repeated DatasetContext datasets = 3;
    repeated AccessOperation general_operations = 4;
}
```
For the ingest use-case the relevant field is general_operations that does not refer to a particular dataset. However, it includes only the operation type, e.g. WRITE, and the destination. This is not enough - attributes such as data residency, data sensitivity are missing. 
Example of a rule: data that contains personal sensitive information and was generated in X cannot be written to Y.

**Comment by roee88** [comment]
For the ingest use case please see https://github.com/IBM/the-mesh-for-data/issues/221#issuecomment-753658641. The suggestion is to support multiple catalog connectors instead and avoid introducing uncataloged assets. We may want to close this issue until we settle on #221 and #224 first.

**Comment by shlomitk1** [comment]
Closing this issue.
