### ISSUE TITLE
Use a single namespace for blueprint deployment

### ISSUE THREAD

**Issue by froesef** [IBM/the-mesh-for-data#257]
Using a single namespace for all blueprints makes many aspects of the mesh for data easier:
- easier to find created blueprints
- easier to remove blueprints (without some finalizers being blocked by namespace deletion)
- more restrictive RBAC. The mesh does not need full access but can be restricted to certain namespaces.

The initial proposal is to use one namespace for blueprints different from m4d-system. (e.g. m4d-blueprints)

**Comment by ronenkat** [comment]
@froesef what are the change implications:
1. what code is impacted
2. does this apply to blueprint? or plotter? or both. what is the impact for multi-cluster?
3. any concerns related to multi tenancy or isolation between tenants?
do we have a consensus for the need and the solution? or should this be in discussions?

**Comment by roee88** [comment]
@ronenkat we had a discussion about that and decided to give it a try because the current situation is too complex to handle, especially in multicluster. It applies to blueprints. The main concern is indeed isolation but we don't have it implemented yet and since we control all module deployments it seems reasonable to assume that we will be able to handle it when we implement isolation (or revert this if we won't be able to).

**Comment by froesef** [comment]
> 1/2. what code is impacted

Only the plotter code as @shlomitk1 will be moving the application code to only produce plotter objects. So the plotter decides which namespace to deploy the blueprint in.

> 3. any concerns related to multi tenancy or isolation between tenants?
>    do we have a consensus for the need and the solution? or should this be in discussions?

If we use a namespace that only the mesh for data system controls we should be good even with multiple tenants as we can use prefixes to distinguish between those as well. I'm not entirely sure how the isolation will look like but at the moment the pros that we get out of this overweigh this.

**Comment by roee88** [comment]
Don't remember why we decided to keep it open, but #304 and #305 should fill the missing gaps.
