### ISSUE TITLE
manager: provide a correct status to the data user

### ISSUE THREAD

**Issue by shlomitk1** [IBM/the-mesh-for-data#27]
- Problem statement:  
M4dApplication resource should provide the data user with the correct status - whether the data is ready to be used, whether there was a failure to allocate the required resources for copying/accessing the data, etc. The orchestration status (readiness or failure of the modules constructing the blueprint) should be reflected in the blueprint status, since m4dApplication does not have access to the orchestrated modules directly. Currently, the orchestration status is not reflected in the blueprint CRD, thus not reported to m4dApplication and to the data user. The goal of this issue is to collect the orchestration status (ready or failed) and report it in the status of the relevant m4dapplication CRD.
- Proposed solution: 
The idea is to use  [kstatus package](https://github.com/kubernetes-sigs/cli-utils/tree/master/pkg/kstatus) for collecting the resource statuses. This will work for standard resources such as deployments and also for any resource that uses Ready condition to indicate its readiness status. For other resources (such as implicit copies) we specify in m4dModule the field to look for and the expected status for both success and failure.
- Affected components: manager
- Required changes: add a section to m4dModule describing conditions for status update, e.g.
     ```
 kind: BatchTransfer
      successCondition: status.status == SUCCEEDED
      failureCondition: status.status == FAILED
      errorMessage: status.error
```

**Comment by roee88** [comment]
Just a note, kstatus also works for https://github.com/kubernetes-sigs/cli-utils/tree/master/pkg/kstatus#conditions and not just Ready field.

**Comment by roee88** [comment]
We can follow and see if Helm adopts it instead of coding on our own https://github.com/helm/helm/issues/8661

**Comment by shlomitk1** [comment]
> 
> 
> Just a note, kstatus also works for https://github.com/kubernetes-sigs/cli-utils/tree/master/pkg/kstatus#conditions and not just Ready field.

In case of conditions, they are checking for two types: Stalled and Reconciling.

**Comment by roee88** [comment]
Right, thanks

**Comment by ronenkat** [comment]
@shlomitk1 can you extend the description of the issue to include:
* what is the problem we are solving
* what components are affected
* what the new behaviour will be
* what user facing changes will take place (and how will it be used)
It will help clarify what we want to achieve.
