### ISSUE TITLE
manager: provide a code for accessing a dataset

### ISSUE THREAD

**Issue by shlomitk1** [IBM/the-mesh-for-data#28]
- Problem statement: 
After the data is available for use (copied to a new location, credentials injected, ...), the data user needs to receive some code/instructions how to access the data.
- Assumptions:
  - All read modules provide such code. Currently, we have arrow-flight module that provides the python code to access the data.
  - This code is available after the Helm chart of the module is installed in Notes field.  See https://github.com/helm/helm/blob/367277afc22809d34dfd61bc9c07f5805fae3365/pkg/release/info.go#L35
  - A single read module is responsible for all data sets.
- Proposed solution:
  After a read module is properly installed, the blueprint controller will copy the code from the release Notes into the blueprint status. When the blueprint state is ready, the manager will copy this code into m4dApplication status.

**Comment by simanadler** [comment]
Please include in the issue (1) what is the problem? - ex: you state that the user needs to receive the python code for accessing the data ... but why doesn't the data user know how to access the data? i.e. the datamesh may move the data, no credentials are needed, etc (2) assumptions - ex: a module exists that will return the needed information.  what are our current modules that can do this? (3) proposed solution

**Comment by shlomitk1** [comment]
@cdoron @roee88  Please change in NOTES.txt file the hard-coded asset name, similar to
`r'{"asset": "{{ .Values.source.connection.s3.object_key}}"}'))`

**Comment by shlomitk1** [comment]
@simanadler I don't think we need to have separate data access instructions for each data set. A future enhancement will be to provide ALL datasets at once to the read module, thus it makes sense to provide a code for accessing all data sets.

**Comment by simanadler** [comment]
@shlomitk1 I would imagine that the data user will not always want to load all the data sets at the same time.  Perhaps we need to provide the option to load all, or load specific data sets.

**Comment by shlomitk1** [comment]
> 
> 
> @shlomitk1 I would imagine that the data user will not always want to load all the data sets at the same time. Perhaps we need to provide the option to load all, or load specific data sets.

It's only "usage example". Users can modify the code as they like. I envision a `for` loop over all asset names, when users can copy the instructions as-is and then delete the asset names that are not loaded. I believe it is more convenient than copying instructions for each data asset and trying to combine them together (deleting redundant imports, renaming variables, etc.)
I suggest we keep a single info string in the status rather than a map of strings per dataset id.

**Comment by roee88** [comment]
Open an issue in the flight module repo please. The PR to resolve the issue described here shouldn't care and it only shows the notes however they are, right?

**Comment by shlomitk1** [comment]
> 
> 
> Open an issue in the flight module repo please. The PR to resolve the issue described here shouldn't care and it only shows the notes however they are, right?

Right.

**Comment by shlomitk1** [comment]
@roee88 Opened https://github.com/IBM/the-mesh-for-data-flight-module/issues/7
