### ISSUE TITLE
Remove unused istio import

### ISSUE THREAD

**Issue by roee88** [IBM/the-mesh-for-data#315]
https://github.com/IBM/the-mesh-for-data/blob/10b0cab98e407c12e9e8cd64520ea645d25c29ca/manager/main.go#L18

`manager/main.go` adds Istio networking api to the schema but we're not using it.

**Comment by roee88** [comment]
@shlomitk1 how come the go.mod didn't change? I think you forgot to run `go mod tidy` (or make verify).

**Comment by shlomitk1** [comment]
> 
> 
> @shlomitk1 how come the go.mod didn't change? I think you forgot to run `go mod tidy` (or make verify).

You are right... Submitted new PR to fix this.
