### ISSUE TITLE
Change deployment of Vault in third_party/vault to use helm chart

### ISSUE THREAD

**Issue by revit13** [IBM/the-mesh-for-data#320]
The Vault deployment and undeployment should use existing chart installation under charts/ directory.

**Comment by revit13** [comment]
@hunchback @roee88 Does it make sense to use hack/make-rules/helm.mk similar to what is does in modules directory?

**Comment by roee88** [comment]
Your issue is unclear to me. We didn't remove `hack/install.sh` or updated the docs yet because it's still work in progress. As a developer and contributor you can however start using https://github.com/IBM/the-mesh-for-data/blob/master/charts/Makefile to deploy what it currently supports.

**Comment by revit13** [comment]
@roee88 OK I understand, I will close this issue then and open a new one to work on charts/ in particular for vault installation.
