### ISSUE TITLE
Improve CI process

### ISSUE THREAD

**Issue by froesef** [IBM/the-mesh-for-data#36]
The CI process currently takes quite some time and can be improved.
First progress has been made by @hunchback [here](https://github.com/IBM/the-mesh-for-data/pull/34)

This issue should be a collection of ideas that can be done in order to further speed up the build.
Please edit put a +1 and name if you agree with the steps.

optimization | vote | status
------------ | ------------- | ------------- 
Improve warm-cache and make install-tools | +1 (ffr) | [first steps here](https://github.com/IBM/the-mesh-for-data/pull/34)
Using external object store for caching. Possibly using an external object store from the standard Travis CI one may result in faster cache upload/download speeds. (There are also different custom caching scripts that could be used) | |
Deploy phase optimization (specifically egeria should only run for master branch as it has a long setup time) | | [done](https://github.com/IBM/the-mesh-for-data/pull/34)
Try a single job instead of multiple stages. Has the advantage that some compilation and cache initialization is shared. The disadvantage is that everything would run in sequence. Another possibility is to have two jobs (one runs verify+test) the other (build+deploy+integration tests + image deploy(master only)) | +1 (ffr) +1 (rs) |
Split go tests into small and larger tests. (Larger run in integration tests) | +1 (ffr) |
Disable egeriaconnector tests until there actually are tests. Currently there are no tests so maven is called to run nothing | +1 (ffr) |
Use local images to test deployments and run integration tests. Currently images from master branch are used which is a bug. | +1 (rs) |
Disable `go vet` and `go fmt` when executing `make test`. Those are executed in `make verify` | +1 (ffr) +1 (rs) | [PR](https://github.com/IBM/the-mesh-for-data/pull/41)
Remove tests that only test Kubernetes CRUD operations (e.g. blueprint_controller_test.go or blueprint_types_test.go). If no functionality of the controller is tested but only if CRUD works we're testing the kubernetes APIs...that should be covered by Kubernetes itself when we're just using the APIs.  | +1 (ffr) |
Rewrite the `make e2e-run` to run against a deployed mesh instance. Thus the test should be a client that is posting CRDs against a Kubernetes cluster and checks if the results are as expected. | +1 (ffr) +1 (rs) |

**Comment by hunchback** [comment]
@froesef some comments:
- the `cache.1` phase takes 80+ seconds, related to restoring the go mod cache directory, how can this be improved?
- single job means we kill parallelism, although if this improves our overall performance then I am not opposed
- regarding images: would like to enable running integration tests on tagged images (which can reside on the public repo) and if tests path then we can tag these images to latest
- tests which only test CRUD need to either be extended or removed
- the e2e test takes much to long, and has to be re-written and improved and parallelized (possibly using go)

**Comment by roee88** [comment]
blueprint_controller_test.go used to test that the current modules are deplyed (before we moved to Helm). I would rather keep those and have a task for writing actual tests.

**Comment by roee88** [comment]
> Disable go vet and go fmt when executing make test. Those are executed in make verify

As mentioned in the https://github.com/IBM/the-mesh-for-data/pull/41 this is true for `make build` as well

**Comment by roee88** [comment]
@froesef I think that most of this is done. Can we reflect what else we want to do in a comment? or just close this and open concrete issue if and when needed?

**Comment by roee88** [comment]
Important parts are already implemented. For further improvements new issues can be opened as required.
