### ISSUE TITLE
Deleting files from a persistent bucket

### ISSUE THREAD

**Issue by shlomitk1** [IBM/the-mesh-for-data#366]
We have two use-cases for copying data:
- implicit copy: a temporary bucket is allocated. It is deleted (along with all objects) upon deletion of m4dapplication.
- ingesting data from another catalog: a persistent bucket is created. It is not deleted upon deletion of m4dapplication.

The current behavior is that upon deletion a batchtransfer deletes the objects inside a bucket, which causes problems in the second use-case and is not required for the first use-case.

**Comment by froesef** [comment]
The `BatchTransfer` has a parameter `spec.noFinalizer` that can be set to true. That way the finalizer is not called and the data is not deleted.
