### ISSUE TITLE
Updating the quick-start in the website

### ISSUE THREAD

**Issue by tomersolomon1** [IBM/the-mesh-for-data#39]
The quick start in the website doesn't explain properly:
https://ibm.github.io/the-mesh-for-data/docs/setup/quickstart/

I think we should create first a readme with instructions that work, and then create the corresponding page in the website.

**Comment by roee88** [comment]
Website pages are similar to readme files, no need for duplication. Just modify https://github.com/IBM/the-mesh-for-data/blob/master/website/content/docs/setup/quickstart/index.md

**Comment by ronenkat** [comment]
Resolved by #107 #97 and #59
