### ISSUE TITLE
Publish Helm charts

### ISSUE THREAD

**Issue by roee88** [IBM/the-mesh-for-data#399]
Push charts on tag to a charts repository.

Following option 3 in discussion https://github.com/IBM/the-mesh-for-data/discussions/313 

A GitHub workflow will be triggered on tags to create a PR in a charts repository. The charts repository will use helm releaser.

**Comment by ronenkat** [comment]
Is a chart repo a better approach than publishing to gh-pages?

**Comment by roee88** [comment]
It's using gh-pages (see https://github.com/helm/chart-releaser-action)
