### ISSUE TITLE
Problem with the notebook sample

### ISSUE THREAD

**Issue by Mohammad-nassar10** [IBM/the-mesh-for-data#407]
In the instructions of the notebook sample https://ibm.github.io/the-mesh-for-data/docs/usage/notebook-sample/
there is a problem in the vault login step. After the step of:
          kubectl port-forward -n m4d-system svc/vault 8200:8200 &
We open http://localhost:8200 on the browser, select "method" as "username" and login using username "data_provider" and password "password". We get an error of "Authentication failed: missing client token".

**Comment by cdoron** [comment]
I also tried:
```
$ vault login -address=http://127.0.0.1:8200 -method=userpass username=data_provider password=password 
Handling connection for 8200
Error authenticating: Error making API request.
URL: PUT http://127.0.0.1:8200/v1/auth/userpass/login/data_provider
Code: 400. Errors:
* missing client token 
```

**Comment by revit13** [comment]
It seems that the error occurs because a file called the-mesh-for-data/connectors/helpers/deploy.sh which set AUTH_METHOD=USERPASS was deleted.

**Comment by roee88** [comment]
@revit13 this sounds related to https://github.com/IBM/the-mesh-for-data/tree/master/connectors/vault only. There are two scripts there, can it be added to them?

This is all kind of obsolete really. If it's too much work we may want to wait a week or so and see if it's still relevant.

**Comment by revit13** [comment]
It seems to fit_vault_init.sh however the secrets are placed in a new vault server as opposed to putting them in the existing Vault instance  that in the control-plane so there might be additional minor adjustments to do to make the demo work properly.

**Comment by revit13** [comment]
Rethinking about it, it might be better to revisit this after the planned code changes as I am not sure how relevant the scripts are to the demo. @cdoron and myself worked on adding userpass auth path to Vault manually to make it work with the demo.
