### ISSUE TITLE
Dependency on oc introduced

### ISSUE THREAD

**Issue by elsalant** [IBM/the-mesh-for-data#422]
hack/install.sh seems now to have a dependency on OpenShift:
oc delete securitycontextconstraints --ignore-not-found egeria-restricted
./deploy.sh: line 17: oc: command not found
make: *** [Makefile:7: deploy] Error 127

**Comment by ronenkat** [comment]
@rohithdv can you look at how to exchange the use of 'oc' with 'kubectl' in https://github.com/IBM/the-mesh-for-data/blob/master/third_party/egeria/deploy.sh lines 17, 41-43 ?

**Comment by cdoron** [comment]
@ronenkat : I think that this problem appeared when the WITHOUT_OPENSHIFT variable changed from "true" to "false" (line 6)

**Comment by ronenkat** [comment]
@elsalant please check if the problem persist when changing line 6 to ": ${WITHOUT_OPENSHIFT=true}".
Thank you @cdoron

**Comment by Mohammad-nassar10** [comment]
I also got the same error. I think you can run "WITHOUT_OPENSHIFT=false ./hack/install.sh" instead. It worked for me.

**Comment by elsalant** [comment]
@cdoron Well, it gets past the problem with the oc command, but it now times out on 
+ helm install egeria egeria-base --namespace=egeria-catalog
Error: failed post-install: timed out waiting for the condition

Trying this as a dry-run gives: 
salant@fogprotect:~/the-mesh-for-data/third_party/egeria$ helm install egeria egeria-base --namespace=$NAMESPACE --dry-run
Error: failed to download "egeria-base" (hint: running `helm repo update` may help)
 Running helm repo update does not help.  Neither does undeploying egeria and redeploying
(This may not be connected with the WITHOUT_OPENSHIFT=true issue though....)

**Comment by rohithdv** [comment]
> @rohithdv can you look at how to exchange the use of 'oc' with 'kubectl' in https://github.com/IBM/the-mesh-for-data/blob/master/third_party/egeria/deploy.sh lines 17, 41-43 ?

I tried to change oc with kubectl. However I think the command is specific to oc. I get the following error: 

<img width="827" alt="image" src="https://user-images.githubusercontent.com/59818576/111190758-6beea280-85dd-11eb-9507-7d6fab0dbc2c.png">

@ronenkat @roee88 @elsalant

**Comment by roee88** [comment]
> @cdoron Well, it gets past the problem with the oc command, but it now times out on
> 
> * helm install egeria egeria-base --namespace=egeria-catalog
>   Error: failed post-install: timed out waiting for the condition
> * kubectl describe pods egeria-base-platform-0  -n egeria-catalog
>   Name:           egeria-base-platform-0
>   Namespace:      egeria-catalog
>   Priority:       0
>   Node:           
>   Labels:         app.kubernetes.io/component=platform
>   app.kubernetes.io/instance=egeria
>   app.kubernetes.io/name=egeria-base
>   controller-revision-hash=egeria-base-platform-5bdb5fb676
>   statefulset.kubernetes.io/pod-name=egeria-base-platform-0
>   Annotations:    
>   Status:         Pending
>   IP:
>   IPs:            
>   Controlled By:  StatefulSet/egeria-base-platform
>   Containers:
>   egeria:
>   Image:      docker.io/odpi/egeria:2.6
>   Port:       9443/TCP
>   Host Port:  0/TCP
>   Liveness:   http-get https://:9443/open-metadata/platform-services/users/garygeeke/server-platform/origin delay=0s timeout=1s period=10s #success=1 #failure=6
>   Readiness:  http-get https://:9443/open-metadata/platform-services/users/garygeeke/server-platform/origin delay=0s timeout=1s period=10s #success=1 #failure=6
>   Startup:    tcp-socket :9443 delay=30s timeout=1s period=10s #success=1 #failure=25
>   Environment Variables from:
>   egeria-env        ConfigMap  Optional: false
>   egeria-autostart  ConfigMap  Optional: false
>   Environment:        
>   Mounts:
>   /deployments/data from data (rw)
>   /extlib from extlib (rw)
>   /var/run/secrets/kubernetes.io/serviceaccount from egeria-base-token-m7gnm (ro)
>   Conditions:
>   Type           Status
>   PodScheduled   False
>   Volumes:
>   data:
>   Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
>   ClaimName:  data-egeria-base-platform-0
>   ReadOnly:   false
>   extlib:
>   Type:      ConfigMap (a volume populated by a ConfigMap)
>   Name:      egeria-extlib
>   Optional:  false
>   egeria-base-token-m7gnm:
>   Type:        Secret (a volume populated by a Secret)
>   SecretName:  egeria-base-token-m7gnm
>   Optional:    false
>   QoS Class:       BestEffort
>   Node-Selectors:  
>   Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
>   node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
>   Events:
>   Type     Reason            Age   From               Message
>   
>   Warning  FailedScheduling  52m   default-scheduler  error while running "VolumeBinding" prebind plugin for pod "egeria-base-platform-0": Failed to bind volumes: timed out waiting for the condition
>   Warning  FailedScheduling  32m   default-scheduler  error while running "VolumeBinding" prebind plugin for pod "egeria-base-platform-0": Failed to bind volumes: timed out waiting for the condition
>   Warning  FailedScheduling  22m   default-scheduler  error while running "VolumeBinding" prebind plugin for pod "egeria-base-platform-0": Failed to bind volumes: timed out waiting for the condition
>   Warning  FailedScheduling  12m   default-scheduler  error while running "VolumeBinding" prebind plugin for pod "egeria-base-platform-0": Failed to bind volumes: timed out waiting for the condition
> 
> Running helm repo update does not help. Neither does undeploying egeria and redeploying

Can you please open a separate issue? Please provide details on the cluster being used and any other information that can help reproduce this problem.
