### ISSUE TITLE
Change the way user secret reference is passed to the connectors

### ISSUE THREAD

**Issue by shlomitk1** [IBM/the-mesh-for-data#441]
Currently, connectors receive appName/appNamespace string inside a request, e.g. notebook/default. Based on this string, they access vault to retrieve credentials in m4d/user-creds/appName/appNamespace/system. 
Following https://github.com/IBM/the-mesh-for-data/pull/398, connectors should receive a link to vault plugin for reading a secret.
@revit13 - please describe what information needs to be passed to the connectors and how to configure vault/connectors for this purpose.

**Comment by revit13** [comment]
As for what information needs to be passed to the connectors, this should be somehow similar to the information passed to the modules to retrieve dataset credentials using Vault client:
        1) address:  Vault address, example: http://vault.m4d-system:8200/ - this might be taken by the connectors directly from m4d-config configMap
        2) AuthPath is the path to auth method used to login to Vault i.e  v1/auth/kubernetes/login - the manager extracts that from cluster-metadata configMap of the cluster.
        3) Role is the Vault role used for retrieving the credentials, example: "connector"  - this should be passed to the connector or placed in m4d-config configMap. Please see more details below.
        4) SecretPath is the path of the secret holding the credentials in Vault, for example
        /v1/kubernetes-secrets/example?namespace=m4d-system
As for the SecretPath  - the Vault path in which the plugin is enabled (for example kubernetes-secrets) comes from the connector - it is currently hard-coded in the connector code, for example katalog connector knows the path in Vault that it needs to use to read dataset creds. As opposed to the modules part of this field (the plugin path) should be known to the connector. the secret details should be passed to the connector.

Here is a description of how to use those values with Vault client to get the secret:
https://ibm.github.io/the-mesh-for-data/contribute/module/#credential-management

As for how to configure vault/connectors for this purpose:

To allow a connector to access that path we need to: 
1) define policy to allow to access all secrets in that path- I currently use a script to add such policy but the proper way is to define it once in the plugin installation after the plugin is enabled.
2) Add role to connect identity to policy: in this case the identity is the service account of the connector and the policy is the one mentioned above. I use a script to add role to the modules in m4d-blueprints but that functionality should be moved to the manager. As for the connectors I am not sure if the manager should add such role as this role should be defined once for each connector so we can insert that to the script as well. Anyway, to add a role the kueberetes auth path of the cluster should be known together with the policy name and the connector service account name.
