### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by roee88** [IBM/the-mesh-for-data#457]
Add CODE_OF_CONDUCT.md to the root directory of the project. For example, using https://www.contributor-covenant.org/version/2/0/code_of_conduct/code_of_conduct.md. 

This requires an email contact for reporting issues (i.e. replacing `[INSERT CONTACT METHOD]`)

**Comment by ronenkat** [comment]
Lets adopt the change that was made at https://github.com/IBM/repo-template/pull/9, changing the contact to the list of people in MAINTAINERS.md, and put a list of people.

**Comment by roee88** [comment]
I don't think that tying it to MAINTAINERS.md makes sense. It should be ~2 people that would actually handle reports related to code of conduct.
