### ISSUE TITLE
undeploy requires disk space

### ISSUE THREAD

**Issue by elsalant** [IBM/the-mesh-for-data#464]
I ran out of disk space trying to install M4D and so then tried to do a make undeploy.

Unfortunately, the first directory it tries to undeploy from is secret-provider, and in secret-provider/deploy/deploy.sh the code is:

kustomize_build() {
        local operation=$1
        local pass=$2
        local TEMP=$(mktemp -d)
        cp -r base/* $TEMP

The cp will immediately fail if there is no room left, failing the undeploy.  Is there any reason to copy to $TEMP if we are doing an undeploy?

**Comment by roee88** [comment]
We have an issue for deleting the secret provider https://github.com/IBM/the-mesh-for-data/issues/432 and we're almost done moving to Helm install instead of kustomize so I would rather not invest here.
