### ISSUE TITLE
Charts: mismatch in the webhook-service name

### ISSUE THREAD

**Issue by shlomitk1** [IBM/the-mesh-for-data#519]
While m4d charts install webhook-service, batch transfer validation requires m4d-webhook-service.

**Comment by roee88** [comment]
Please provide more context. Preferably a link to where "batch transfer validation requires m4d-webhook-service."

**Comment by shlomitk1** [comment]
https://github.com/mesh-for-data/the-mesh-for-data-mover/blob/master/movement_controller.yaml#L1406

**Comment by roee88** [comment]
But this isn't part of the project. The movement controller is deployed with the m4d chart. 

I assume that the file you linked is for testing by @froesef. It includes the MutatingWebhookConfiguration/ValidatingWebhookConfiguration on its own.

**Comment by shlomitk1** [comment]
I got an error when creating a BatchTransfer. I assume MutatingWebhookConfiguration was not configured using m4d.
