### ISSUE TITLE
public messaging app

### ISSUE THREAD

**Issue by hunchback** [IBM/the-mesh-for-data#52]
The two most common non-IRC messaging applications used for OSS are:

slack - which is commonly used but suffers from a cap on message history of 10k. I created a workspace named the-mesh-for-data accessible at: https://join.slack.com/t/the-mesh-for-data/shared_invite/zt-i6dsu8w4-oMdwrGWWVF6mVdnKVNXITg 

discord - also a very good option initially used for gaming but becoming more and more popular for OSS. I created a server names the-mesh-for-data https://discord.gg/vTJ4DhG

@ronenkat, @roee88 and @froesef please comment

**Comment by ronenkat** [comment]
Thank you @hunchback.
I suggest we wait with the decision for a while and use github mechanisms (issues, PRs) for now.

**Comment by ronenkat** [comment]
Closing. Will re-open at the appropriate time.
