### ISSUE TITLE
Feature: Control plane security

### ISSUE THREAD

**Issue by roee88** [IBM/the-mesh-for-data#57]
## Problem description

The control plane currently includes the following components:
1. manager
1. connector services (possibly 3rd parties)
1. secret provider service (to be refactored; separate issue to be opened) 
1. Hashicorp Vault instance

The connectors expose a GRPC endpoint, the secret provider exposes an HTTP endpoint, the Vault instance exposes an HTTP endpoint. The problem:
1. These endpoints are accessible by any service in the cluster
1. The traffic between the control plane components is not encrypted

## Scope

This issue excludes the secret provider that would be addressed separately.

This issue is an umbrella issue for the following items:
1. Only allow control plane traffic within the m4d-system namespace
1. [optional] Restrict access to a connector (by default allowed only from manager, add option to enable connector-connector)
1. [optional] Restrict access to Vault (by default allowed only from manager; add option to enable connector?)
1. Encrypt all traffic 

## Proposed approach

- Use network policies for restricting access within the m4d-system namespace and between the specific components
- Encrypt traffic using Istio by enabling sidecar injection to all control plane components

## Proposed sub-issues

1. Create NetworkPolicy to disallow ingress traffic from outside the m4d-system namespace (w/ exclusions)
1. Enable Istio sidecar injection to manager
1. Enable Istio sidecar injection to connectors
1. Enable encryption for Vault

**Comment by simanadler** [comment]
Would it make sense for the connectors to run in a different namespace, and not in m4d-system?  You would still need to control access to them of course.

**Comment by roee88** [comment]
I think having the control plane in one namespace is simpler. What would be the benefit of separating it? Wouldn't it only add complexity?

**Comment by roee88** [comment]
Closing this as there are no concrete followups here. The work on credentials in multicluster should address remaining items.
