### ISSUE TITLE
Enforcement Action restructure

### ISSUE THREAD

**Issue by etykha** [IBM/the-mesh-for-data#65]
Enforcement Action restructure to more hierarchical format, to reduce number of enforcement actions in the taxonomy and enable different levels of specification for desired governance action. 
This issue has an assumption that enforcement action implementation (e.g. masking algorithm) should be consistent both with policy-manager enforcement implementation behind a policy if such exists, like in WKC or any other policy manager that has also PEP, and between our modules used in the same application.
Full discussion of this issue and suggested solution here: https://ibm.ent.box.com/notes/730332532445

**Comment by roee88** [comment]
Closing, will be addressed as part of the taxonomy work.
