### ISSUE TITLE
Submission of credentials to external systems

### ISSUE THREAD

**Issue by roee88** [IBM/the-mesh-for-data#79]
This issue discusses the handling of `system credentials`, required to access external systems such as the data catalog.

# Problem description 

Currently, the flow is that system credentials are stored to vault directly (by a human user or by the sample GUI) using root access to vault. Any component that needs to read these credentials (such as connectors) read them directly from vault, again using privileged access. This issue proposes an alternative to enable a more secure solution that is both natural to Kubernetes users (that use `kubectl`) and that a managed UX can build upon.

# Proposal 

## Scope

- Excluding dataset credentials (to be addressed by another issue)
- Excluding system credentials provided by the administrator (e.g., for the vault connector)
- The user actor is tied to a `M4DApplication` resource. We do not distinguish the deployer of a workload from a data user. The `M4DApplication` abstraction is flexible enough to capture both cases. Work needed to properly support data users in different scenarios (beyond the abstraction itself) is out of scope.
- A managed stack (specific connectors and UI that work together) may choose to use a different method than what is proposed here. We can't and don't really want to force it if the managed stack has a better way to achieve the same (in its own env).

## New stuff

A Kubernetes `Secret` resource should be created by the user, holding the relevant system credentials:
```yaml
apiVersion: v1
data:
  <system-name>: <system specific credentials>
  <system-name>: <system specific credentials>
kind: Secret
metadata:
  name: <any name the user chooses>
  namespace: <the same namespace as the M4DApplication>
type: Opaque
```
Both `<system-name>` and `<system specific credentials>` should be filled according to the documentation of the connector(s) in use. `name` can be the same as the `M4DApplication` but we don't force it (e.g., to allow multiple  `M4DApplication` resources in the same namespace to refer to the same secret).

The `M4DApplication` structure would change to hold an optional reference to the secret:
```yaml
apiVersion: app.m4d.ibm.com/v1alpha1
kind: M4DApplication
metadata:
  name: <any name the user chooses>
  namespace: <the same namespace as the Secret>
spec:
  credentials: <the same name as the Secret>
...
```

The `pkg/security/credentials/system` package will include functions:

1. SetSystemCredentials that internally creates and applies a Secret object and sets it in the `M4DApplication`:
    ```go
    func SetSystemCredentials(namespace, name string, credentials map[string]string) error
    ```
1. GetSystemCredentials that reads the system credentials for a specific `M4DApplication` and a specific target system:
    ```go
    func GetSystemCredentials(namespace, name, systemName string) error
    ```

Fields `namespace` and `name` are of the `M4DApplication`. The implementation of `SetSystemCredentials` is simplified to save the secret using the same name as the `M4DApplication`, but `GetSystemCredentials` does not assume that.

Note that these calls won't work without proper RBAC (`SetSystemCredentials` for write secrets in the user namespace, `GetSystemCredentials` for read secrets from the user namespace).

## Integration

1. Add system credentials to Egeria connector (none of the connectors in `/connectors` currently accept user provided credentials. We should investigate whether the Egeria connector needs this and if so use it as an example)
1. Add documentation for system credentials as part of connectors docs
1. Add documentation for system credentials as part of `M4DApplication` submission
1. The `manager` component to use `GetSystemCredentials`. Requires ClusterRole for manager to read secrets (already has it).
1. The sample GUI to internally use `SetSystemCredentials` and `GetSystemCredentials`. Requires Role for GUI to read/write secrets in user namespace.
1. (Future) cli to internally to use `SetSystemCredentials` and `GetSystemCredentials`.

For reading by connectors we have two options to choose from **ACTION REQUIRED**:
1. Connectors will internally use `GetSystemCredentials`. For non go connectors a sidecar exposing this call through grpc/rest will be provided (localhost access). Requires ClusterRole for connectors to read secrets. 
1. A sidecar to manager will expose a grpc/rest server exposing GetSystemCredentials (only accessible by the connectors, similar to https://github.com/IBM/the-mesh-for-data/issues/57). 

## Compatibility

1. Compatibility with the existing method to read/write system credentials is not preserved. All code must change to use the new GetSystemCredentials/SetSystemCredentials.
1. Future changes:  If the implementation of GetSystemCredentials/SetSystemCredentials changes to use something different than a Secret, then it should be transparent to existing components and should not break existing user deployments. The changed implementation must preserve the existing functionality in `GetSystemCredentials` if a secret is detected (until deprecation period is over). Sidecars are updated with control plane / connectors upgrades. After deprecation period usage error should indicate that an upgrade might be needed.

### Using Vault

1. User stores system credentials to the internal Vault instance. Would require setting up Vault upfront with the users base to allow them to login and interact with their own space within Vault (tied to control plane, `M4DApplication`, and user) which seems difficult to achieve for a Kubernetes user base.
1. User stores system credentials by sending them to a service installed to a namespace that they can access and port-forward to. The service stores the credentials to Vault to its own space within vault (achieved using dynamic policies and tying to the `ServiceAccount` of the service). An awkward flow that is also not really natural to Kubernetes users.
1. User submits `M4DApplication` via a managed environment that is user-aware. The system stores the credentials to Vault under a user-specific prefix. A role is created for each connector to be able to read these credentials. This can be implemented using the sample managed environment using dynamic rules in Vault. Seems impossible to implement without requiring a managed environment.

### M4D Sealed secrets

Implement a new `M4DSealedSecret` CRD that stores encrypted data.
The goal is lowering the exposure of the credentials so that they can't be seen by other users that have Kubernetes access to the same namespace. Depending on the implementation, possibly also adds some protection against Kubernetes administrators.

Similar to [sealed-secrets](https://github.com/bitnami-labs/sealed-secrets), the control plane holds an RSA keypair and a new cli tool (`m4dctl`) allows creating encrypted secrets that only the control plane can read. Unlike sealed-secrets there is no automatic conversion to regular `Secret` resources since this is the opposite of what we try to achieve.

Can be a future project external to M4D.

### Secret to Vault operator

Monitors `Secret` resources that has a specific label. For a mathed `Secret` resource, a the controller copies the `data` within the `Secret` to Vault. Finally, it removes the `Secret` resource. 

This limits the time window that the `Secret` can be viewed by other users that has access to it. However, the removal phase is a bit intrusive and might even cause problems when the `Secret` is deployed as part of a larger deployment (e.g., by Razee or Helm). The flow is a bit too complex and without extra benefits if the removal phase is not part of it.

**Comment by simanadler** [comment]
@roee88 Looks fine to me.  What is your reasoning though for moving only external system credentials to k8s secrets?  For example, would it make sense to store the object store accounts used for implicit copies in k8s secrets instead of vault as well ... and similarly the accounts used for the (future) ingest scenario?  These are of course set up by an M4D admin rather than a data user, but what is the reasoning for using vault for that and secrets for system credentials provided by data users?

**Comment by roee88** [comment]
I agree with you. That will all be handled as part of `dataset credentials` in a future issue. I'm taking a staged approach here.

**Comment by simanadler** [comment]
> I agree with you. That will all be handled as part of `dataset credentials` in a future issue. I'm taking a staged approach here.

Perhaps you should state that explicitly?  Currently it sounds like you are planning on using different solutions for different types of credentials?

**Comment by roee88** [comment]
This is blocked because of concerns with cluster tenancy model in multicluster setting. Basically the creation of `Secret` near `M4DApplication` in a remote cluster will not work. We need an alternative for the cluster tenancy model.

**Comment by roee88** [comment]
Creation of M4DApplication in remote clusters becomes an issue to handle with our current codebase anyway. I suggest to move forward without considering it.

**Comment by roee88** [comment]
Closed in favor of https://github.com/IBM/the-mesh-for-data/discussions/253
