### ISSUE TITLE
ci: add support for releases

### ISSUE THREAD

**Issue by roee88** [IBM/the-mesh-for-data#82]
Problem: Currently we don't do releases at all. This includes: no GitHub releases, no GitHub tags, no tags on containers

Requirements:
- track releases using tags (e.g., release-v0.0.1)
- tag images in CI when running from a tag branch
- optionally create GitHub releases with release notes
- optionally support vertioned docs in website

Personal suggestion for now is to only do a minimal change to the CI to tag images the branch name for tag branches. Then when ready @ronenkat will create a GitHub tag for the first release that will trigger the CI.

**Comment by roee88** [comment]
@hunchback want to take this one?

**Comment by hunchback** [comment]
I  plan to follow a an example from a small sized project such as razee: https://github.com/razee-io/Razee/releases/tag/0.0.9

**Comment by roee88** [comment]
All non optional requirements are implemented (some more PRs might be opened for fixes). @hunchback please open concrete issues for future improvements when needed.
