### ISSUE TITLE
Cluster-prepare phase

### ISSUE THREAD

**Issue by tomersolomon1** [IBM/the-mesh-for-data#83]
##### Problem
1. Vault is currently installed during the `cluster-prepare` phase in the Makefile. However, this is currently also done by the installation script, with the user's control.

2. Also some registry secret is created. This secret is probably a leftover from the time before the images were hosted in public registries.

See https://github.com/IBM/the-mesh-for-data/blob/master/Makefile#L25

##### Suggestion
Remove these two operations from the `cluster-prepare` phase.

FYI @hunchback

**Comment by roee88** [comment]
I think it should be the other way around. The install script should not call cluster-prepare. It only takes third_party/cert-manager from it, which conflicts with many existing clusters that already have it. Instead the instructions should state that cert-manager needs to be installed in the cluster (possibly with a hint that third_party/cert-manager can be used, though it doesn't add much value over https://cert-manager.io/docs/installation/).

@hunchback does that sound right?

**Comment by roee88** [comment]
> Vault is currently installed during the cluster-prepare phase in the Makefile. However, this is currently also done by the installation script, with the user's control.

@hunchback is this still relevant after the move to helm? Should we close this issue?

**Comment by roee88** [comment]
To be resolved when the work on helm is finished
