### ISSUE TITLE
Taxonomy for dataset credentials and connection properties. 

### ISSUE THREAD

**Issue by roee88** [IBM/the-mesh-for-data#96]
# Problem description

There are different connection types (s3, kafka, etc.). Each connection type has a different structure for credentials (e.g., s3 credentials includes access key and secret key) and connection properties (e.g., endpoint).

However, the exact structure for each type is undefined. We have inconsistencies between different components in the project (connectors and modules). For example, `mover` expects `{'data': {'access_key': '<value>', 'secret_key': '<a3026f48a13ff1246e26b09f99237eb457bec35e4321ab12>'}, ...}` while `flight` expects  `{'access_key': '<value>', 'secret_key': '<value>'}`

# Proposed solution

Document a fixed mapping that must be followed by all connectors and modules. 
The preferred structure for credentials is one that can easily be used when adding a secret to vault through its UI.

**Comment by froesef** [comment]
Actually the mover can deal with data being in `data` or outside like flight. But we were running into the problem that the mover was expecting `accessKey` and `secretKey`. So I completely agree that there is an issue and that we should unify this!

One way is that we could fix the credentials in the protobuf return type of the connector (and use the same structure for the secretProvider)

Thus in the example below a connector would set the fields where it has a value for. As protobuf structs in go get generated with `json:"field,omitempty"` when converting a struct to JSON it would result in an object that only has the fields that are not empty. This would allow for a standard mapping of credentials from the connectors.
```
message Credentials {
    string access_key = 1; 
    string secret_key = 2; 
    string user = 3; 
    string password = 4; 
    string api_key = 5; 
}
```

**Comment by roee88** [comment]
@froesef why the preference to put all credential forms in a single message? Don't we also want to attach it to the connection type to associate the expected credentials for each connection type? 

I wonder if we need to have more structure here, e.g., to differentiate between S3 and COS because the latter can have an API key without HMAC credentials so a module with code that requires access_key and secret_key won't fit. Does the mover module support both?

**Comment by froesef** [comment]
No the mover is currently based on the open-source stocator plugin that is working with HMAC credentials. As I understand we'd have to switch to the `ibm-sdk` version of it to support API key. I chose the HMAC version as these can also be used with different S3 implementations.

**Comment by rohithdv** [comment]
@roee88 @froesef just a query: is the proposal in this PR the following: Provide more structure to the credentials information instead of returning a JSON string as we are doing now as provided in the proto [here](https://github.com/IBM/the-mesh-for-data/blob/71c611af2fafcf9705b83757dcc3556f5d7ec654/pkg/connectors/protos/data_credential_response.proto#L11)? or is the PR not talking about this [proto](https://github.com/IBM/the-mesh-for-data/blob/master/pkg/connectors/protos/data_credential_response.proto#L11) ?

**Comment by shlomitk1** [comment]
> 
> 
> @roee88 @froesef just a query: is the proposal in this PR the following: Provide more structure to the credentials information instead of returning a JSON string as we are doing now as provided in the proto [here](https://github.com/IBM/the-mesh-for-data/blob/71c611af2fafcf9705b83757dcc3556f5d7ec654/pkg/connectors/protos/data_credential_response.proto#L11)? or is the PR not talking about this [proto](https://github.com/IBM/the-mesh-for-data/blob/master/pkg/connectors/protos/data_credential_response.proto#L11) ?

@rohithdv This proto exactly - provide dataset credentials in a structured way instead of a json string as today.
