### ISSUE TITLE
kubeflow installation script doesn't work on mac 

### ISSUE THREAD

**Issue by roee88** [IBM/the-mesh-for-data#98]
[install_kubeflow.sh](https://github.com/IBM/the-mesh-for-data/blob/master/samples/kubeflow/install/kubeflow/install_kubeflow.sh) downloads kfctl for linux only. It should support OSX as well, like the scripts in `hack/tools`.

**Comment by roee88** [comment]
@ronenkat can you please share the commands that worked for you in osx?

**Comment by ronenkat** [comment]
@roee88 I run "wget https://github.com/kubeflow/kfctl/releases/download/v1.0.2/kfctl_v1.0.2-0-ga476281_darwin.tar.gz" and the rest of the script worked fine.
